### ISSUE TITLE
A Example

### ISSUE THREAD

**Issue by alexandre1985** [patmood/wildcard-subdomains#10]
I have a website with Node.js and Express that is on server `alex.mysite.org`.  
I want to add a subdomain, for example, `test.alex.mysite.org`. So I have this code:

    var express = require('express');
    var app = express();
    
    var httpProxy = require('http-proxy');
    var proxy = httpProxy.createProxyServer();
    
    var wildcardSubdomains = require('wildcard-subdomains');
    
    app.use(wildcardSubdomains({
            namespace: '_sub',
            whitelist: ['www', 'app1'],
    }));
    
    app.all('/_sub/test/*', function(req, res) {
            proxy.web(req, res, {target: 'http://127.0.0.1:3001'});
    });
    
    app.all('/*', function(req, res) {
            proxy.web(req, res, {target: 'http://127.0.0.1:3000'});
    });
    
    app.listen(80);

Everything was working, but I added the 'wildcard-subdomains' module and their respective code and now accessing my website online is giving a 404.  
Locally `127.0.0.1:3000` and `127.0.0.1:3001` is working.  
Can someone help me?  

**UPDATE:**
The problem seems that *wildcard-subdomains* is detecting all the out of LAN traffic (traffic using the `alex.mysite.org`) as a '/_sub/alex/' route. Is there a way to only consider the subdomain before `alex.mysite.org` (*for example:* `test.alex.mysite.org` would became '/_sub/test/')?

**Comment by alexandre1985** [comment]
**UPDATE:**
The problem seems that *wildcard-subdomains* is detecting all the out of LAN traffic (traffic using the `alex.mysite.org`) as a '/_sub/alex/' route. Is there a way to only consider the subdomain before `alex.mysite.org` (*for example:* `test.alex.mysite.org` would became '/_sub/test/')?

**Comment by patmood** [comment]
Unfortunately that use case isn't supported with this version. I will make sure it's included with the next release, but I don't have time to work it it right now. As a workaround, you could remove `'alex'` from the subdomains list with middleware. Before using `wildcardSubdomains`, you could add something like:

```
app.use(function(req, res, next) {
  req.subdomains = req.subdomains.filter(function(sub) { return sub !== 'alex' })
  next()
})
```
I haven't tested the above, but it might give you some ideas.
