### ISSUE TITLE
Is there a way to use this with gulp?

### ISSUE THREAD

**Issue by npearson72** [patmood/wildcard-subdomains#2]
I don't know enough about node, and am using a Yeoman generator to spin up an angular app:

https://github.com/Swiip/generator-gulp-angular

I'm using it to talk to an api, but I would like to listen on wildcard subdomains.

Can you help?

**Comment by patmood** [comment]
This is a module for the express web framework. It's used for handling subdomain routes on a node server. Angular is a client side framework which will be served from a single domain.

You won't be able to "listen" on wildcard domains from the client, you need to use a server.

**Comment by npearson72** [comment]
I understand that, but the yeoman generator I pointed you to uses some type of server to serve up angular -- at least for development. You type in 'gulp serve' in the command line and it starts up. I'm not full sure where gulp ends and the server (assuming some type of node server) starts, but was hoping this plugin could be injected into that stack to work for my needs.

Anyway, thanks for your help.

**Comment by patmood** [comment]
No worries! The server that yeoman gives you is just for development. You would need to setup your own express server and handle the subdomain routes in there.
