### ISSUE TITLE
Apache proxying, req.subdomain issue

### ISSUE THREAD

**Issue by CodeOrRoad** [patmood/wildcard-subdomains#4]
Hi, I really liked your library and I am using it. I made few modifications to suit my requirement. Anyhow I would suggest one improvement and one bug.

In cases, where apache/nginx works infront of nodejs, it is better to use `req.headers['x-forwarded-host']` instead of `req.headers.host`

You are storing the subdomains data in req.subdomain. I could not get the data using the same in my final route. I changed it to req._subdomain = subdomain and accessed the same and I got the data successfully.

**Comment by patmood** [comment]
Excellent suggestions! I'm going to update it, add a few tests, and publish a new version on npm.

**Comment by patmood** [comment]
It looks like `req.hostname` is ideal and uses the `x-forwarded-host` in the appropriate scenarios.

You may need to enable trust proxy as shown in the express tests here https://github.com/expressjs/express/blob/master/test/req.hostname.js#L77

**Comment by patmood** [comment]
I've updated the package on npm. Take a look at this article for more info about running express behind proxies http://expressjs.com/en/guide/behind-proxies.html
