### ISSUE TITLE
How i create a subdomain for each user then handle that way?

### ISSUE THREAD

**Issue by surendrakumar1992** [patmood/wildcard-subdomains#6]
I am working on MEAN application. I want to create a unique subdomain for each user. If any one visit that unique sub domain then information will show accordingly. I also test this to my localhost.

Thanks in advance

**Comment by patmood** [comment]
That's exactly what this package was made for!

Once you add it to your middleware, add something like this to your routes:

```
app.get('/_sub/:username', function (req, res) {
    // Get user info here and render the page
}
```

When testing on localhost, go to `username.vcap.me` to test subdomains. Vcap.me is a domain that points back to your local machine. Great for testing.

**Comment by surendrakumar1992** [comment]
Thanks for your quick response.
I got your point and i know it will work now query is that how i point 'N' number of sub domain. Each new user i want to create sub domain. Can i handle this with enter in etc/host file.

Thanks in advance

**Comment by patmood** [comment]
The snippet I posted has a path param `username` which will be any subdomain.

For example:

```
app.get('/_sub/:username', function (req, res) {
    var username = req.query.username
    // Get user from database by username
    // Render the page with that users specific info
})
```

That route will handle any username and the path param will be different each time.

**Comment by DeepakTDS** [comment]
How to change vcap to another name 'xyxcompany'
